version: '3'
services:
  db:
    build: pg_docker/
  msgboard:
    build: .
    ports:
      - "18089:8089"
    volumes:
      - /var/log:/var/log
    depends_on:
      - db
    environment:
      - PQ_CONN=host=db dbname=msgboard user=postgres client_encoding=utf-8